### ISSUE TITLE
Kontrol untuk upload lampiran

### ISSUE THREAD

**Issue by bowvernon110391** [bcsoetta/sibape#15]
gunakan `b-file` dari `Bootstrap-Vue`. Elemen inti dari upload adalah:

- `filename` : nama file
- `filesize`: ukuran file dalam bytes
- `mime/type`: MIME-type dari file yg diupload

Bisa ditambahkan metadata lainnya, nantinya di server, file akan disimpan dengan nama yang unik. Selama file diupload, tampilkan progress bar (apabila memungkinkan), minimal spinner. Setelah selesai, tampilkan dalam bentuk yang bisa dibuka (url based), atau image viewer untuk file gambar.

**UNTUK FILE BESAR GUNAKAN KONTROL FILE LAIN!!**

**Comment by bcsoetta** [comment]
done, upload bisa via browse atau webcam
