### ISSUE TITLE
Interface untuk pembatalan

### ISSUE THREAD

**Issue by bcsoetta** [bcsoetta/sibape#22]
Perlu dibuat:
- [x] interface untuk melihat surat pembatalan yang sudah direkam
- [x] input dan edit surat pembatalan
- [x] select surat pembatalan 
- [x] modalviewdialog utk memilih surat pembatalan (gunakan SelectPembatalan) (takes `id`, and `doctype` or `uri`
- [x] custom **NUKE** button to delete locked document

**Comment by bowvernon110391** [comment]
So far it's usable, no need to go deeper
