### ISSUE TITLE
Tarif PPh (%)

### ISSUE THREAD

**Issue by bcsoetta** [bcsoetta/sibape#5]
- [ ] Agar dibuat fleksibel (bisa input tarif yang tidak ada di opsi)
- [x] Tambahkan tarif 10% dan 20%

**Comment by bowvernon110391** [comment]
Sudah ditambahkan tarif 10% dan 20% per commit 25e5fe6f2a6e00f27aabf2de008635c90337d309

Untuk opsi fleksibel, nanti diopen lagi aja tiketnya
